### ISSUE TITLE
I can't runClient

### ISSUE THREAD

**Issue by eqwdsamosadomsa** [MeteorDevelopment/meteor-addon-template#37]
[14:46:26] [ERROR] [FabricLoader/GameProvider]: Minecraft game provider couldn't locate the game! The game may be absent from the class path, lacks some expected files, suffers from jar corruption or is of an unsupported variety/version.
[14:46:26] [ERROR] [FabricLoader/]: Uncaught exception in thread "main"
java.lang.RuntimeException: Minecraft game provider couldn't locate the game! The game may be absent from the class path, lacks some expected files, suffers from jar corruption or is of an unsupported variety/version.
	at net.fabricmc.loader.impl.launch.knot.Knot.createGameProvider(Knot.java:214)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:130)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

**Comment by Lncvrt** [comment]
> [14:46:26] [ERROR] [FabricLoader/GameProvider]: Minecraft game provider couldn't locate the game! The game may be absent from the class path, lacks some expected files, suffers from jar corruption or is of an unsupported variety/version. [14:46:26] [ERROR] [FabricLoader/]: Uncaught exception in thread "main" java.lang.RuntimeException: Minecraft game provider couldn't locate the game! The game may be absent from the class path, lacks some expected files, suffers from jar corruption or is of an unsupported variety/version. at net.fabricmc.loader.impl.launch.knot.Knot.createGameProvider(Knot.java:214) at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:130) at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

If this isn't an issue you should probably close it. It's likely a issue you did and this is almost a year old issue
