### ISSUE TITLE
NoLambdaFactoryException #17

### ISSUE THREAD

**Issue by u2hfuefhgef** [MeteorDevelopment/meteor-addon-template#51]
meteordevelopment.orbit.NoLambdaFactoryException: No registered lambda listener for 'addon.new1.modules.ModuleExample'.
	at meteordevelopment.orbit.EventBus.getLambdaFactory(EventBus.java:188)
	at meteordevelopment.orbit.EventBus.getListeners(EventBus.java:166)
	at meteordevelopment.orbit.EventBus.lambda$getListeners$2(EventBus.java:146)
	at meteordevelopment.orbit.EventBus.getListeners(EventBus.java:158)
	at meteordevelopment.orbit.EventBus.unsubscribe(EventBus.java:114)
	at meteordevelopment.meteorclient.systems.modules.Modules.onGameLeft(Modules.java:310)
	at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:83)
	at meteordevelopment.orbit.EventBus.post(EventBus.java:53)
	at net.minecraft.client.MinecraftClient.handler$zfe000$meteor-client$onDisconnect(MinecraftClient.java:3856)
	at net.minecraft.client.MinecraftClient.disconnect(MinecraftClient.java)
	at net.minecraft.client.MinecraftClient.disconnect(MinecraftClient.java:2268)
	at net.minecraft.client.gui.screen.GameMenuScreen.disconnect(GameMenuScreen.java:119)
	at net.minecraft.client.session.report.AbuseReportContext.tryShowDraftScreen(AbuseReportContext.java:52)
	at net.minecraft.client.gui.screen.GameMenuScreen.method_19836(GameMenuScreen.java:100)
	at net.minecraft.client.gui.widget.ButtonWidget.onPress(ButtonWidget.java:95)
	at net.minecraft.client.gui.widget.PressableWidget.onClick(PressableWidget.java:48)
	at net.minecraft.client.gui.widget.ClickableWidget.mouseClicked(ClickableWidget.java:145)
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement.java:38)
	at net.minecraft.client.Mouse.method_1611(Mouse.java:99)
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:414)
	at net.minecraft.client.Mouse.onMouseButton(Mouse.java:99)
	at net.minecraft.client.Mouse.method_22686(Mouse.java:180)
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor.java:102)
	at net.minecraft.client.Mouse.method_22684(Mouse.java:180)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3509)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:238)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1352)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
	
	
	how to fix

**Comment by MineGame159** [comment]
You forgot to change [this](https://github.com/MeteorDevelopment/meteor-addon-template/blob/master/src/main/java/com/example/addon/AddonTemplate.java#L42) line of code in your addon
