### ISSUE TITLE
2 Errors when trying to run

### ISSUE THREAD

**Issue by Grammf** [MeteorDevelopment/meteor-addon-template#6]
```
java.lang.NoClassDefFoundError: org/spongepowered/asm/mixin/transformer/FabricMixinTransformerProxy
java.lang.ClassNotFoundException: org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy
```

**Comment by Grammf** [comment]
```> Task :runClient FAILED
[23:12:07] [main/INFO] (FabricLoader/GameProvider) Loading for game Minecraft 1.17.1
[23:12:07] [main/INFO] (FabricLoader) Loading 6 mods:
	- addon-template 0.3
	- baritone 1.7.0
	- fabricloader 0.12.3
	- java 16
	- meteor-client 0.4.6-1314
	- minecraft 1.17.1
[23:12:07] [main/INFO] (FabricLoader/Mixin) SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/Users/egork/.gradle/caches/modules-2/files-2.1/net.fabricmc/sponge-mixin/0.10.4+mixin.0.8.4/2db026cfe22893ef3ed94af152265400b81bc0e3/sponge-mixin-0.10.4+mixin.0.8.4.jar Service=Knot/Fabric Env=CLIENT
[23:12:07] [main/INFO] (FabricLoader/Mixin) Loaded Fabric development mappings for mixin remapper!
[23:12:07] [main/INFO] (FabricLoader/Mixin) Compatibility level set to JAVA_16
Exception in thread "main" java.lang.RuntimeException: Mixin transformation of net.minecraft.client.main.Main failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:224)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:133)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:566)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
Caused by: java.lang.NoClassDefFoundError: org/spongepowered/asm/mixin/transformer/FabricMixinTransformerProxy
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1010)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
Caused by: java.lang.NoClassDefFoundError: org/spongepowered/asm/mixin/transformer/FabricMixinTransformerProxy

	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:149)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at meteordevelopment.meteorclient.MixinPlugin.onLoad(MixinPlugin.java:43)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.onLoad(PluginHandle.java:119)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onSelect(MixinConfig.java:709)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.selectConfigs(MixinProcessor.java:498)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:460)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:222)
	... 7 more
Caused by: java.lang.ClassNotFoundException: org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
Caused by: java.lang.ClassNotFoundException: org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy

	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 24 more

Execution failed for task ':runClient'.
> Process 'command 'C:\Users\egork\.jdks\openjdk-16.0.2\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.```

**Comment by arlomcwalter** [comment]
its cause you updated the mappings manually, not our problem

**Comment by Grammf** [comment]
ok thx
